/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mystore.app_store;

/**
 *
 * @author User
 */
public class Navegador extends javax.swing.JPanel {

    /**
     * Creates new form Navegador
     */
    public Navegador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navegator = new javax.swing.JPanel();
        btnCatalogo = new javax.swing.JButton();
        btnInicio = new javax.swing.JButton();
        btnProducto = new javax.swing.JButton();
        btnUsuario = new javax.swing.JButton();
        btnConfig = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        navegator.setBackground(new java.awt.Color(43, 141, 156));

        btnCatalogo.setBackground(new java.awt.Color(43, 141, 156));
        btnCatalogo.setText("CATALOGO");
        btnCatalogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnInicio.setBackground(new java.awt.Color(43, 141, 156));
        btnInicio.setText("INICIO");
        btnInicio.setToolTipText("");
        btnInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInicioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInicioMouseEntered(evt);
            }
        });
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        btnProducto.setBackground(new java.awt.Color(43, 141, 156));
        btnProducto.setText("PRODUCTOS");
        btnProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProductoMouseClicked(evt);
            }
        });

        btnUsuario.setBackground(new java.awt.Color(43, 141, 156));
        btnUsuario.setText("USUARIOS");
        btnUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUsuarioMouseClicked(evt);
            }
        });

        btnConfig.setBackground(new java.awt.Color(43, 141, 156));
        btnConfig.setText("CONFIGURACION");
        btnConfig.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout navegatorLayout = new javax.swing.GroupLayout(navegator);
        navegator.setLayout(navegatorLayout);
        navegatorLayout.setHorizontalGroup(
            navegatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navegatorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(navegatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCatalogo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnProducto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addComponent(btnUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addComponent(btnConfig, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addComponent(btnInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE))
                .addContainerGap())
        );
        navegatorLayout.setVerticalGroup(
            navegatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navegatorLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        add(navegator, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 490));
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMouseClicked
//        PageLogin p1 = new PageLogin();
//        p1.setSize(970, 490);
//        p1.setLocation(0,0);
//
//        content.removeAll();
//        content.add(p1, BorderLayout.CENTER);
//        content.validate();
//        content.repaint();
    }//GEN-LAST:event_btnInicioMouseClicked

    private void btnInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMouseEntered

    }//GEN-LAST:event_btnInicioMouseEntered

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductoMouseClicked
//        PageProduct pgProduct = new PageProduct();
//        pgProduct.setSize(970, 490);
//        pgProduct.setLocation(0,0);
//
//        content.removeAll();
//        content.add(pgProduct, BorderLayout.CENTER);
//        content.validate();
//        content.repaint();
    }//GEN-LAST:event_btnProductoMouseClicked

    private void btnUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsuarioMouseClicked
//        PageUsuario pgUsuario = new PageUsuario();
//        pgUsuario.setSize(970, 490);
//        pgUsuario.setLocation(0,0);
//
//        content.removeAll();
//        content.add(pgUsuario, BorderLayout.CENTER);
//        content.validate();
//        content.repaint();
    }//GEN-LAST:event_btnUsuarioMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCatalogo;
    private javax.swing.JButton btnConfig;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnProducto;
    private javax.swing.JButton btnUsuario;
    private javax.swing.JPanel navegator;
    // End of variables declaration//GEN-END:variables
}
