/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mystore.app_store;

import com.mystore.app_store.servicioApi.ApiLogin;
import com.mystore.app_store.servicioApi.ApiUsuario;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class PageUsuario extends javax.swing.JPanel {

    
     ApiUsuario api = new ApiUsuario();
   ApiLogin apiLogin = new  ApiLogin ();
        Object[][] rowData = (Object[][]) 
           api.mostrarUsuario();
        
        String nuevosDatos = rowData.toString();
        
  //  PageLogin pageLogin = new  PageLogin();
   //  String username = pageLogin.getUsuario().getText();
  // String  password = new String(pageLogin.getClave().getPassword());
    
    /**
     * Creates new form PageUsuario
     */
    public PageUsuario() {
        initComponents();
     //   apiLogin.enviarLogin(this.username, this.password);
        listar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsuario = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(970, 490));

        tablaUsuario.setBackground(new java.awt.Color(153, 255, 153));
        tablaUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaUsuario);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(421, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaUsuario;
    // End of variables declaration//GEN-END:variables

public void listar(){

   
   DefaultTableModel model = new DefaultTableModel(rowData, new Object[]{"name", "email", "phone", "phone2", "estate"});
    tablaUsuario.setModel(model);
    
    }

}
